spring.application.name=license-plate-game
spring.datasource.url=jdbc:postgresql://localhost:5432/license-plate-game
spring.datasource.username=newuser
spring.datasource.password=changeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=saQZM3kSADzy2XPFIuqhyXAs28A495Ta8R2QBeTKr8o
jwt.expiration=3600000
